name: Node version in Var
on: 
  workflow_dispatch:
  pull_request:

env:
  NODE_VERSION: 14
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{env.NODE_VERSION}}
        - name: run version
          run: node -v
        - name: run install + test
          shell: bash
          run: |        
            npm install
            npm test